### ISSUE TITLE
Fail regexp matching in `frog-version`

### ISSUE THREAD

**Issue by yfzhe** [greghendershott/frog#253]
Background: I am trying to use circle-ci and racket-docker to deploy my frog-based blog. Racket-docker seems to download the "pre-compiled" package from the package server:
```
Resolving "frog" via https://download.racket-lang.org/releases/7.5/catalog/
Resolving "frog" via https://pkg-build.racket-lang.org/server/built/catalog/
Downloading https://pkg-build.racket-lang.org/server/built/pkgs/frog.zip
```

When I run `raco frog --build`, it failed, with the following error message:
```
match: no matching clause for "(module info setup/infotab (#%module-begin (define package-content-state (quote (built \"7.5\"))) (define version \"0.30\") (define collection (quote multi)) (define deps (quote ((\"base\" #:version \"6.2\") \"find-parent-dir\" \"html-lib\" (\"markdown...
  location...:
   /root/.racket/7.5/pkgs/frog/frog/private/main.rkt:180:2
  context...:
```
In [the line 181 of frog/private/main](https://github.com/greghendershott/frog/blob/master/frog/private/main.rkt#L181), it use regexp `^#lang info\n+\\(define version \"([^\"]+)\"` to match the version number. But the error message indicates the info.rkt is expended, it is `(module info setup/infotab ....)` not `#lang info ...`
